name: Sync to Emmo00 Personal Repo

on:
  push:
    branches:
      - main
  pull_request:
    types: [closed]
    branches:
      - main

permissions: 
  contents: write
  pull-requests: write

jobs:
  sync:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up Git user
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Push to Emmo00 personal repo
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_TOKEN }}
          repository: Emmo00/borderless-admin-frontend
          branch: main
          directory: .
          force: true
